### ISSUE TITLE
watermark.py list index out of range

### ISSUE THREAD

**Issue by brooksvb** [chinapandaman/PyPDFForm#245]
When writing a PDF file, I get the following error:
```
Traceback (most recent call last):
  File "/home/brooksvb/Projects/SpreadsheetCombiner/FormFiller.py", line 33, in <module>
    form.fill({
  File "/home/brooksvb/.local/lib/python3.9/site-packages/PyPDFForm/middleware/wrapper.py", line 361, in fill
    FillerCore().fill_v2(self.stream, self.elements)
  File "/home/brooksvb/.local/lib/python3.9/site-packages/PyPDFForm/core/filler.py", line 283, in fill_v2
    return WatermarkCore().merge_watermarks_with_pdf(
  File "/home/brooksvb/.local/lib/python3.9/site-packages/PyPDFForm/core/watermark.py", line 155, in merge_watermarks_with_pdf
    if watermarks[i]:
IndexError: list index out of range
```

My code looks like
```
	form = PyPDFForm2(pdfPath)
	print(form.elements.keys)

	with open(outputPath, 'wb+') as output:
		output.write(
			form.fill({
				'QCredit': '5000.63'
			}).read()
		)
		output.close()
```

I printed the value of `watermarks` before the problematic loop in `watermarks.py`, and it's an empty list `[ ]`.

I changed https://github.com/chinapandaman/PyPDFForm/blob/b3684204bc469ba87547ca90c27ebd41571d1fa1/PyPDFForm/core/watermark.py#L155
to `            if i < len(watermarks):`, but after this change I get a new error:
```
Traceback (most recent call last):
  File "/home/brooksvb/Projects/SpreadsheetCombiner/FormFiller.py", line 33, in <module>
    form.fill({
  File "/home/brooksvb/.local/lib/python3.9/site-packages/PyPDFForm/middleware/wrapper.py", line 360, in fill
    self.stream = TemplateCore().remove_all_elements(
  File "/home/brooksvb/.local/lib/python3.9/site-packages/PyPDFForm/core/template.py", line 27, in remove_all_elements
    for j in reversed(range(len(elements))):
TypeError: object of type 'NoneType' has no len()
```
I did some digging into this and I see that the last page in `pdf.pages` simply doesn't have an `/Annot` key.

Any guidance on this issue? I've resorted to trying multiple other PDF libraries for filling forms and have not had luck. The odd thing is I was using this exact form last night to test writing out fields with this library and it worked just fine.

**Comment by chinapandaman** [comment]
`	form = PyPDFForm2(pdfPath)
	print(form.elements.keys)

	with open(outputPath, 'wb+') as output:
		output.write(
			form.fill({
				'QCredit': '5000.63'
			}).read()
		)
		output.close()
`
Could you post the PDF form you used for this snippet? Also, what version are you running on?

**Comment by brooksvb** [comment]
`pip show pypdfform` returns
```
Name: PyPDFForm
Version: 1.0.0
Summary: The Python library for PDF forms.
Home-page: https://github.com/chinapandaman/PyPDFForm
Author: Jinge Li
Author-email: None
License: UNKNOWN
Location: /home/brooksvb/.local/lib/python3.9/site-packages
Requires: pillow, pdfrw, reportlab
Required-by:
```

This is the pdf
[formreformatted.pdf](https://github.com/chinapandaman/PyPDFForm/files/7447866/formreformatted.pdf)

**Comment by chinapandaman** [comment]
Thanks for unveiling a major bug in the library. The root cause of your issue is that this PDF form's last page doesn't have any element, which was an edge case the library didn't catch before.

Anyway, I did a fix for it and made a release. If you upgrade the package to the newest version it should work now.

**Comment by brooksvb** [comment]
Thank you for the quick response! It seems the new version of the code is not causing any issues for me as of this moment.
