### ISSUE TITLE
Alignment of form field content

### ISSUE THREAD

**Issue by appcoders** [chinapandaman/PyPDFForm#282]
Thanks for the great library. I have form fields that are defined horizontally centered. Unfortunately, they are always left aligned. Can I change this? Thank you.

**Comment by chinapandaman** [comment]
Hello, could you post the snippet and the PDF form you used? Thanks.

**Comment by appcoders** [comment]
Sorry for delay. Here are the PDF files and the code.

```
import os

from PyPDFForm import PyPDFForm2

PATH_TO_DOWNLOADED_SAMPLE_PDF_FORM = os.path.join(
    os.path.expanduser("~/Downloads"), "testformcentered.pdf"
)  # Change this to where you downloaded the sample PDF form

PATH_TO_FILLED_PDF_FORM = os.path.join(
    os.path.expanduser("~/Downloads"), "outputform.pdf"
)  # Change this to where you wish to put your filled PDF form

with open(PATH_TO_FILLED_PDF_FORM, "wb+") as output:
    result = output.write(
        PyPDFForm2(PATH_TO_DOWNLOADED_SAMPLE_PDF_FORM)
        .fill(
            {
                "name": "Hans Mustermann",
                "fulladdress": "Musterstr. 12, 82903 Musterdorf, Musterland",
                "advisorname": "Karl Test"
            },
        )
        .read()
    )
    print (result)


```
[testformcentered.pdf](https://github.com/chinapandaman/PyPDFForm/files/10089695/testformcentered.pdf)
[outputform.pdf](https://github.com/chinapandaman/PyPDFForm/files/10089696/outputform.pdf)

**Comment by chinapandaman** [comment]
Hello, I made a minor bump. Go ahead and upgrade your version and let me know how it works. Thanks.

**Comment by appcoders** [comment]
Thanks for your quick reply and fix. 
I updated today
`Successfully installed PyPDFForm-1.1.1 pdfrw-0.4 pillow-9.3.0 reportlab-3.6.12`
but still the content is left aligned.
[result.pdf](https://github.com/chinapandaman/PyPDFForm/files/10101692/result.pdf)

**Comment by appcoders** [comment]
@chinapandaman  Awesome! Works. Many thanks for your quick fix.

**Comment by chinapandaman** [comment]
> 



> @chinapandaman Awesome! Works. Many thanks for your quick fix.

Sorry if I got confused. I got two emails, one with your comment says you did your upgrade and the content is still left aligned, and this comment I quoted. Did you modify your earlier comment? If so I assume it’s working for you now so feel free to close this issue.

**Comment by appcoders** [comment]
@chinapandaman Sorry for confusion, everything works fine 👍
