### ISSUE TITLE
Issue with some characters

### ISSUE THREAD

**Issue by tomazbc** [chinapandaman/PyPDFForm#383]
Hi!
Some characters from my language have issues, specifically Đđ, Čč and Ćć. While Š and Ž work fine.
 The ones with issues show up as black squares in the PDF or "n"  if I copy out.
 
 My code otherwise works fine as it names the PDF correctly, just when it comes to PyPDDForm this happens.
 
 Can also reproduce issue in the demo.

**Comment by chinapandaman** [comment]
> Hi! Some characters from my language have issues, specifically Đđ, Čč and Ćć. While Š and Ž work fine. The ones with issues show up as black squares in the PDF or "n" if I copy out.
> 
> My code otherwise works fine as it names the PDF correctly, just when it comes to PyPDDForm this happens.
> 
> Can also reproduce issue in the demo.

Hello,

Without seeing your template and code snippet I cannot say 100%. But I have helped another user with a similar issue like yours except in another language (Chinese in his case). And here are some advices I gave him:

* The annotation name (so the keys of the dictionary) needs to be English. I couldn’t get other languages’ characters supported.
* The value you fill in those elements can be other languages’ characters if you just register the font with those characters (there are examples on how to register fonts in the example doc).

Let me know if this helps you.

**Comment by tomazbc** [comment]
Hi!

I've solved the issue about 1 hour after I wrote it here. I apologize for not updating the thread.


Anyways, the default font that is used by PyPDFForm does not support those characters. After registering a font that does it worked flawlessly.

I was under the assumption it would use the font that is in the PDF form. And we all know "Assumption is the mother of all f... ups" :)

**Comment by chinapandaman** [comment]
> Hi!
> 
> I've solved the issue about 1 hour after I wrote it here. I apologize for not updating the thread.
> 
> Anyways, the default font that is used by PyPDFForm does not support those characters. After registering a font that does it worked flawlessly.
> 
> I was under the assumption it would use the font that is in the PDF form. And we all know "Assumption is the mother of all f... ups" :)
> 
> Thanks for the reply and the awesome package.

Awesome I’m glad it worked out.
