### ISSUE TITLE
Getting error when trying to parse this form

### ISSUE THREAD

**Issue by burinc** [chinapandaman/PyPDFForm#437]
Thanks for a great tool/library:

I am trying to follow the example in the README and keep getting the following error when trying it with the following PDF file.

[USCIS ar-11 form](https://www.uscis.gov/sites/default/files/document/forms/ar-11.pdf)

```
 "/Users/burinc/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/pdfrw/pdfreader.py",
   line 648, in __init__ self.load_stream_objects(trailer.object_streams) File
   "/Users/burinc/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/pdfrw/pdfreader.py",
   line 306, in load_stream_objects offsets.append((int(next()), firstoffset +
   int(next()))) ^^^^^^^^^^^ ValueError: invalid literal for int() with base 10:
   'jð\x7f\xad\x8e\x1c\x17\x16A4Ö¸Eò\x16u'
```

It seems that the package `pdfrw` which `PyPDFForm` depends on are unable to work with this file.

I am able to run the same code with the other PDF file like [ds111 form](https://eforms.state.gov/Forms/ds11.pdf)

Any idea to mitigate this issue?

Thanks

**Comment by chinapandaman** [comment]
Hello,

When I tried to open the problematic form in a PDF editor it says it needs a password otherwise the only thing you can do to it is manually filling the form. Do you know what the password is? I think that might be the issue.

Thanks

**Comment by burinc** [comment]
Hmm, it is the public form that doesn't have any password. I can open it without any issue.

**Comment by chinapandaman** [comment]
I can view it as well, at least in Chrome. But if you were to try to edit it using tools like [this](https://www.docfly.com/dashboard) you will see what I meant.

**Comment by burinc** [comment]
I can see what you mean now. That might be the reason we can't edit the file. Perhaps we should let the user know if we can't open the file due to the above limitation.

e.g. if the file requires a password to edit then let the user know that this tool won't support it.

Thanks.

**Comment by chinapandaman** [comment]
So I did more experiment regarding PDF forms with password. See below snippet:

```python
import os

from PyPDFForm import PdfWrapper
from pypdf import PdfReader, PdfWriter

PATH_TO_DOWNLOADED_SAMPLE_PDF_FORM = os.path.join(
    os.path.join(os.path.dirname(__file__), "pdf_samples", "sample_template.pdf")
)  # Change this to where you downloaded the sample PDF form

PATH_TO_FILLED_PDF_FORM = os.path.join(
    os.path.join(os.path.dirname(__file__), "temp", "output.pdf")
)  # Change this to where you wish to put your filled PDF form

reader = PdfReader(PATH_TO_DOWNLOADED_SAMPLE_PDF_FORM)
writer = PdfWriter()
writer.append_pages_from_reader(reader)
writer.encrypt("password")

with open(PATH_TO_FILLED_PDF_FORM, "wb+") as output:
    writer.write(output)

obj = PdfWrapper(PATH_TO_FILLED_PDF_FORM).fill(
    {
        "test": "test"
    }
)
print(obj.schema)

with open(PATH_TO_FILLED_PDF_FORM, "wb+") as output:
    output.write(obj.read())
```

Here I encrypted the [sample template](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/sample_template.pdf) with a password `password` using the `pypdf` library. And when I attempt to fill the encrypted form nothing gets filled.

When I look at the schema of the encrypted form it looks like this:
```
{'type': 'object', 'properties': {'43b70e46': {'type': 'string'}, '8a3bd359e0': {'type': 'boolean'}, 'df8f2ffceaf2': {'type': 'string'}, 'bfe241d4c8a3de': {'type': 'boolean'}, 'a47522ab781c': {'type': 'string'}, '3d42f8cd28da9d': {'type': 'boolean'}}}
```
So it looks like encrypting the form also changed the names on all the widgets to hashed strings.

Now obviously your form is probably not encrypted using `pypdf` and is also probably encrypted in a different way because it still allows you to view and fill it manually. However case it is, the file stream cannot be read by `pdfrw`.

With everything said, I'm jumping to the following conclusion:

**Comment by burinc** [comment]
Wow, thanks for a details response!

I did a bit of digging myself, it seems that the same file can be processed with `pypdf` without issue.

e.g. I got a similar error when trying to list the fields using `pypdfrw` but I can get the fields without issue using `pypdf`.

```python
from pypdf import PdfReader, PdfWriter
# https://www.uscis.gov/sites/default/files/document/forms/ar-11.pdf
reader = PdfReader("ar-11.pdf")
writer = PdfWriter()

page = reader.pages[0]
fields = reader.get_fields()

writer.append(reader)
# ... more codes
```
I can get the result similar to this:

```
('form1[0].#subform[0].S1_MiddleName[0]',
 {'/FT': '/Tx',
  '/Ff': 8388608,
  '/Parent': {'/Kids': [IndirectObject(293, 0, 5212109072),
                        IndirectObject(294, 0, 5212109072),
                        IndirectObject(295, 0, 5212109072),
                        IndirectObject(296, 0, 5212109072),
                        IndirectObject(297, 0, 5212109072),
                        IndirectObject(298, 0, 5212109072),
                        IndirectObject(299, 0, 5212109072),
                        IndirectObject(300, 0, 5212109072),
                        IndirectObject(301, 0, 5212109072),
                        IndirectObject(302, 0, 5212109072),
                        IndirectObject(303, 0, 5212109072),
                        IndirectObject(304, 0, 5212109072),
                        IndirectObject(305, 0, 5212109072),
                        IndirectObject(306, 0, 5212109072),
                        IndirectObject(307, 0, 5212109072),
                        IndirectObject(308, 0, 5212109072),
                        IndirectObject(309, 0, 5212109072),
                        IndirectObject(310, 0, 5212109072),
                        IndirectObject(311, 0, 5212109072),
                        IndirectObject(312, 0, 5212109072),
                        IndirectObject(313, 0, 5212109072),
                        IndirectObject(314, 0, 5212109072),
                        IndirectObject(315, 0, 5212109072),
                        IndirectObject(316, 0, 5212109072),
                        IndirectObject(317, 0, 5212109072),
                        IndirectObject(318, 0, 5212109072),
                        IndirectObject(319, 0, 5212109072),
                        IndirectObject(320, 0, 5212109072),
                        IndirectObject(321, 0, 5212109072),
                        IndirectObject(322, 0, 5212109072),
                        IndirectObject(290, 0, 5212109072)],
              '/Parent': IndirectObject(292, 0, 5212109072),
              '/T': '#subform[0]'},
  '/T': 'S1_MiddleName[0]',
  '/TU': 'Information About You.  Enter Middle Name (if applicable)'})

```

When trying with `pypdfrw` with similar codes:

```python
pdf = pdfrw.PdfReader("ar-11.pdf")
for page in pdf.pages:
    annotations = page['/Annots']
    if annotations is None: 
        continue
    for annotation in annotations:
         if annotation['/Subtype']=='/Widget':
             if annotation['/T']:
                 key = annotation['/T'].to_unicode()
                 print (key)
```

I got the following errors:

```
 Traceback (most recent call last): File
   "/Users/burinc/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/pdfrw/pdfreader.py",
   line 650, in __init__ self.load_stream_objects(trailer.object_streams) File
   "/Users/burinc/.asdf/installs/python/anaconda3-2023.09-0/lib/python3.11/site-packages/pdfrw/pdfreader.py",
   line 308, in load_stream_objects offsets.append((int(next()), firstoffset +
   int(next()))) ^^^^^^^^^^^ ValueError: invalid literal for int() with base 10:
   'jð\x7f\xad\x8e\x1c\x17\x16A4Ö¸Eò\x16u'

```
I understand that migration to other libraries will take more time and effort.
In this case `
Thanks again for your help and your work!

**Comment by chinapandaman** [comment]
Hello,

Sorry for a delayed response. I know you just closed the issue but you might have done it just a bit early. I just bumped v1.4.1 and with the newest version the following snippet works for me:

```python
import os
from pprint import pprint

from PyPDFForm import PdfWrapper

PATH_TO_DOWNLOADED_SAMPLE_PDF_FORM = os.path.join(
    os.path.join(os.path.dirname(__file__), "temp", "ar-11.pdf")
)  # Change this to where you downloaded the sample PDF form

PATH_TO_FILLED_PDF_FORM = os.path.join(
    os.path.join(os.path.dirname(__file__), "temp", "output.pdf")
)  # Change this to where you wish to put your filled PDF form

obj = PdfWrapper(PATH_TO_DOWNLOADED_SAMPLE_PDF_FORM)
pprint(obj.schema)

with open(PATH_TO_FILLED_PDF_FORM, "wb+") as output:
    output.write(obj.fill(obj.sample_data).read())
```

Feel free to try the above with your own dict instead of `sample_data`. If you run into more issues let me know.

Thanks.

**Comment by burinc** [comment]
Hi @chinapandaman,
This is awesome!
I can confirm that the above form is now working with the new version of this library.
Also, I tried another form e.g. [f1005](https://immi.homeaffairs.gov.au/form-listing/forms/1005.pdf) that used to have problems as well. So far I can fill both form without any issues.

Thanks again for your work.

**Comment by chinapandaman** [comment]
Awesome, I'm glad things worked out.

In fact I want to thank you too for finally unveil the instability of `pdfrw`. As much as I love the library (as a matter of fact it was the only Python PDF library that enabled me to start this project at the time given my experience) neither the original author nor any fork wants to update it anymore. So the idea of switching it to something that's actively maintained has been lingering in my mind for a while. You not only gave me that last push motivation wise, but also made me realize that `pypdf` is now mature enough to switch over (when I first started the project, it wasn't).

So, big thanks to you too!
