### ISSUE TITLE
Altering Existing Checkbox 

### ISSUE THREAD

**Issue by gfleetwood** [chinapandaman/PyPDFForm#516]
Hello. I used the package with an existing template that had checkboxes. The default True tick icon was a bit small. I wanted to try to make it bigger (is that the size parameter in create_widget?) and/or change the button_style. After reading the docs and watching your talk I came up with this that didn't work:

```
from pprint import pprint
from PyPDFForm import PdfWrapper

pdf = PdfWrapper("template.pdf")
pdf.elements['key'].button_style = 'cross'
filled = pdf.fill({'key': True})

with open("output.pdf", "wb+") as output:
    output.write(filled.read())
```

Along the same vein, is there a way to use a circle or cross for a previously existing checkbox's button style? I noticed those options in the docs for creating a new checkbox. (I don't know if the size parameter is related to my first question.)

**Comment by chinapandaman** [comment]
Hello, the button style as of now is not something you can specify to change in your code.

The initial philosophy behind this was that if you want to change the button style, you should change it on the template instead of the code. But now that I think about it I have also provided ways to change text styles so it kinda is a needed feature.

This will take sometime to implement. I’ll look to get it done this week and let you know.

**Comment by gfleetwood** [comment]
@chinapandaman Got it. Thanks. Honestly, I don't care about changing the button style if I can make the tick bigger. Is that also something I need to do on the template itself?

**Comment by chinapandaman** [comment]
The size of the tick is calculated based on the size of the checkbox itself. Honestly I’m surprised it could be too small. Could you attach the template you were talking about so I can take a look at why?

**Comment by gfleetwood** [comment]
@chinapandaman I wouldn't want to share it publicly, but if you're open to a private conversation (maybe on LinkedIn since it's in your bio) I can send it over.

**Comment by chinapandaman** [comment]
Hey, I just bumped v1.4.12. When you get a chance checkout the [new doc](https://chinapandaman.github.io/PyPDFForm/button_style/) and let me know if you run into more issues.

**Comment by gfleetwood** [comment]
@chinapandaman It works like a charm. Thank you for the quick turn around.
