### ISSUE TITLE
Unicode characters missing

### ISSUE THREAD

**Issue by Pleonazm** [chinapandaman/PyPDFForm#532]
Hi

Filling forms with strings containing Unicode characters is buggy and unpredictable

The following script works just fine
```
from PyPDFForm import PdfWrapper
filled = PdfWrapper("sample_template.pdf").fill({"test": "test_1"})
with open("output_sample.pdf", "wb+") as output:
    output.write(filled.read())
```
But with something like the below, some characters are not displayed or black boxes replace them

```
from PyPDFForm import PdfWrapper
filled = PdfWrapper("sample_template.pdf").fill({"test": "test_1 öőúüűóáäöüẞąółżćźæøåñ¿¡"})
with open("output_sample.pdf", "wb+") as output:
    output.write(filled.read())
```

Tested on Windows 7 (Python 3.8) and Linux Mint 21.3 (Python 3.10)
PyPDFForm 1.4.12

When the pdf is opened, the string copied/pasted by hand, it is saved properly in the file.

**Comment by chinapandaman** [comment]
Hello, thanks for reaching out.

I have had a user with [a similar issue](https://github.com/chinapandaman/PyPDFForm/issues/383), and for him the solution was to register the appropriate font(s) for the problematic characters.

Also have you tried the newest [FormWrapper](https://chinapandaman.github.io/PyPDFForm/simple_fill/). I just tried your second snippet except with `FormWrapper` and it worked out fine.

**Comment by chinapandaman** [comment]
Hey @Pleonazm, did my previous comment resolve your issue?

**Comment by Pleonazm** [comment]
Hi

Sorry for the late reply.

Yes, it works with new wrapper.

Also, I noticed that some characters (with the new wrapper) depend on pdf browser you are using.

**Comment by chinapandaman** [comment]
Ya, unfortunately there's not much I can do about that because under the hood it largely depends on whether each PDF browser is able to interpret or has those fonts.

**Comment by Pleonazm** [comment]
I think so.

Just, some info about some quick tests I did, if you are curious:

Windows 7:
FoxitReader - displays blank form, with absolutely no values, and empty fields
Chrome, MS Edge  - everything looks fine

Linux Mint 21:
FoxitReader - some characters missing
Default document browser - everything looks fine

**Comment by chinapandaman** [comment]
Oh this is actually quite normal. Even if you fill these forms manually some PDF browsers will display them with just empty fields.

For instance if you checkout [this PDF](https://github.com/chinapandaman/PyPDFForm/blob/master/pdf_samples/simple/dropdown/dropdown_one.pdf), when GitHub tries to display it it will display the checkboxes and radio buttons, but not the text fields or dropdown fields. However if you download this PDF and open it in Chrome, you will see that all text fields and dropdown fields are actually filled and Chrome will display them properly.

If you want to have consistent display results from different PDF browsers while filling in place, I suggest you flatten the PDF when filling it. It is [supported](https://chinapandaman.github.io/PyPDFForm/simple_fill/) by the library.

**Comment by Pleonazm** [comment]
Well, this is worth remembering.
Thanks for your help, the issue may be closed now, I think.
