### ISSUE TITLE
Cannot parse checkbox's Description

### ISSUE THREAD

**Issue by freaksie** [chinapandaman/PyPDFForm#757]
### Version

PyPDFForm=1.4.37

### Issue Description

Unable to parse the description for the checkbox. This is important info for someone who has no reference to the original template (PDF). 

### Code Snippet

```python
import json
from PyPDFForm import PdfWrapper
pdf_form_schema = PdfWrapper("i-90.pdf").schema
print(json.dumps(pdf_form_schema, indent=4, sort_keys=True))
```

#### Sample of Json Output
```
{
        "P1_checkbox4[1]": {
            "type": "boolean"
        },
        "P1_checkbox4[2]": {
            "type": "boolean"
        },
        "P1_checkbox6c_Unit[0]": {
            "type": "boolean"
        },
        "P1_checkbox6c_Unit[1]": {
            "type": "boolean"
        },
        "P1_checkbox6c_Unit[2]": {
            "type": "boolean"
        }
}


```

### PDF Form Template
[i-90.pdf](https://github.com/user-attachments/files/17710650/i-90.pdf)

### Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/8b08893c-40ba-4583-8614-118533323ff6)

**Comment by freaksie** [comment]
I tried to extract the TU ('/TU'), but its not working 

```
WIDGET_KEY_PATTERNS = [
    {T: True},
    {TU: True},
    {Parent: {T: True, TU: True}},
]
```

**Comment by freaksie** [comment]
Solved

Had to modify some files
Created new function in template.py `get_widget_description`


```
        P1_checkbox4[0]": {
            "description": "Part 1. Information About You. Your Full Name. 4. Has your name legally changed since the issuance of your Permanent Resident Card? Select Yes. (Proceed to Item Numbers 5. A. through 5. C.).",
            "type": "boolean"
        },
        "P1_checkbox4[1]": {
            "description": "Part 1. Information About You. Your Full Name. 4. Has your name legally changed since the issuance of your Permanent Resident Card? Select No (Proceed to Item Numbers 6. A. through 6. I.).",
            "type": "boolean"
        },
        "P1_checkbox4[2]": {
            "description": "Part 1. Information About You. Your Full Name. 4. Has your name legally changed since the issuance of your Permanent Resident Card? Select Not Applicable - I never received my previous card. (Proceed to Item Numbers 6. A. through 6. I.).",
            "type": "boolean"
        },

```

**Comment by chinapandaman** [comment]
Hey thanks for posting, and sorry for a rather late response.

You can open a PR against branch [PPF-757](https://github.com/chinapandaman/PyPDFForm/tree/PPF-757) if you want.

**Comment by chinapandaman** [comment]
Hey @freaksie , if I'm not mistaken [this fork](https://github.com/freaksie/PyPDFForm) is where your changes are at right?

I will be making a version bump of the library on New Year and would like to include your changes. To give me enough time to review/revision them, could you raise your PR against branch [PPF-757](https://github.com/chinapandaman/PyPDFForm/tree/PPF-757) no later then Dec 20th? Thanks.
